//user authentication
export const USER_CREATE = "USER_CREATE";
export const USER_CREATE_FAIL = "USER_CREATE_FAIL";
export const USER_CREATE_SUCCESS = "USER_CREATE_SUCCESS";
export const SIGN_OUT = "SIGN_OUT";
export const REMOVE_ERROR_MESSAGE = "REMOVE_ERROR_MESSAGE";

export const USER_SIGN_IN = "USER_SIGN_IN";
export const USER_SIGN_IN_FAILED = "USER_SIGN_IN_FAILED";
export const USER_SIGN_IN_SUCCESS = "USER_SIGN_IN_SUCCESS";

//Trip
export const CREATE_TRIP_SUCCESS = "CREATE_TRIP_SUCCESS";
export const CREATE_TRIP_FAILED = "CREATE_TRIP_FAILED";
export const FETCH_TRIP_LIST = "FETCH_TRIP_LIST";
