//user authentication
export const USER_CREATE = "USER_CREATE";
export const USER_CREATE_FAIL = "USER_CREATE_FAIL";
export const USER_CREATE_SUCCESS = "USER_CREATE_SUCCESS";
export const SIGN_OUT = "SIGN_OUT";
export const REMOVE_ERROR_MESSAGE = "REMOVE_ERROR_MESSAGE";

export const USER_SIGN_IN = "USER_SIGN_IN";
export const USER_SIGN_IN_FAILED = "USER_SIGN_IN_FAILED";
export const USER_SIGN_IN_SUCCESS = "USER_SIGN_IN_SUCCESS";

//Trip
export const CREATE_TRIP_SUCCESS = "CREATE_TRIP_SUCCESS";
export const CREATE_TRIP_FAILED = "CREATE_TRIP_FAILED";
export const FETCH_TRIP_LIST = "FETCH_TRIP_LIST";

export const GET_TRIP = "GET_TRIP";
export const GET_TRIP_FAIL = "GET_TRIP_FAIL";
export const GET_TRIP_SUCCESS = "GET_TRIP_SUCCESS";

export const ENTER_TRIP_USER = "ENTER_TRIP_USER";
export const ENTER_TRIP_USER_FAILED = "ENTER_TRIP_USER_FAILED";

export const CHANGE_MONEY_SUCCESS = "CHANGE_MONEY_SUCCESS";
export const CHANGE_MONEY_FAILED = "CHANGE_MONEY_FAILED";
